export const RECEIVE_APPLICATIONS = 'RECEIVE_APPLICATIONS'

export const ADD_APPLICATION_REQUEST = 'ADD_APPLICATION_REQUEST'
export const ADD_APPLICATION_SUCCESS = 'ADD_APPLICATION_SUCCESS'
export const ADD_APPLICATION_FAILURE = 'ADD_APPLICATION_FAILURE'

export const DELETE_APPLICATION_REQUEST = 'DELETE_APPLICATION_REQUEST'
export const DELETE_APPLICATION_SUCCESS = 'DELETE_APPLICATION_SUCCESS'
export const DELETE_APPLICATION_FAILURE = 'DELETE_APPLICATION_FAILURE'